### ISSUE TITLE
Is there a list of EEPROM addresses used? And of MIDI Implementation?

### ISSUE THREAD

**Issue by MrMep** [amowry/WARBL2#4]
Hi @amowry 
I need to save some new settings in EEPROM and having a list of address usage would be great.
Also, to add some new functionalities to the config tool, a similar list for MIDI implementation would be useful.

Related to that, I know we have already discussed this in the past, but I think all hard-coded references to EEPROM addresses and MIDI CC/Values in the code should be replaced by defines, so to:
- avoid mistakes
- have an implicit list of values in the code.
- eventually, more easily revise the memory/Midi mappings.

If you want, I can prepare a PR (I'm going to re-do this in any case, in my fork) and keep a detailed track of all substitutions needed.
Let me know

**Comment by amowry** [comment]
Yes, here's the list of MIDI codes and EEPROM locations: https://docs.google.com/spreadsheets/d/1RMybJNk4U3nuWJMf272YrA4IQXBxHd9fxcdVKVG5dME/edit?usp=sharing

Sorry, I've been meaning to add a link to that.

I think that's fine to add defines for all of those--  if you'd like to submit a pull request, that would be great. Thanks!

**Comment by MrMep** [comment]
Thank you!
After the first PR with EEPROM address defines, I'll submit another one with MIDI defines.
All the info from the file you linked above were inserted into Defines.h. I'll do the same with MIDI.
