### ISSUE TITLE
Backward Compatibiliy in Config Tool

### ISSUE THREAD

**Issue by MrMep** [amowry/WARBL2#8]
In WARBL(1) jumpFactor 87 was associated to ED[38] which was CUSTOM_FINGERING_1.
In midi.js we now have:

https://github.com/amowry/WARBL2/blob/a90325da783a1973508743a3fd4cc2dfda353250/webconfig/js/midi.js#L1211-L1221

I guess that we need to add a FW version check, otherwise CUSTOM_FINGERING_1 is never received from WARBL(1).

Or am I missing something?

gl

**Comment by amowry** [comment]
I think you're right-- I'll add a version check after I merge your pull request. Thanks for finding this!
